### ISSUE TITLE
Export/Import per user testen

### ISSUE THREAD

**Issue by CarmenScholte** [slt-programmers/macrologWebapp#16]
Als we over gaan naar een productie omgeving moeten we de export en import functionaliteit goed testen

**Comment by CarmenScholte** [comment]
Test ging goed, export functie lokaal lijkt te werken, import functie werkt ook. 
Nu graag export functie op productie testen aangezien er meerdere users op de PRD database zitten

**Comment by atienkamp** [comment]
```` 
018-09-21T17:24:29.747291+00:00 app[web.1]: 2018-Sep-21 17:24:29.746 ERROR [http-nio-56481-exec-5] o.a.c.c.C.[.[.[.[dispatcherServlet] - Servlet.service() for servlet [dispatcherServlet] in context with path [] threw exception [Request processing failed; nested exception is org.springframework.jdbc.CannotGetJdbcConnectionException: Failed to obtain JDBC Connection; nested exception is java.sql.SQLNonTransientConnectionException: Could not create connection to database server. Attempted reconnect 3 times. Giving up.] with root cause

2018-09-21T17:24:29.747304+00:00 app[web.1]: com.mysql.cj.exceptions.CJException: User 'lkdvzi03wx20qk3f' has exceeded the 'max_questions' resource (current value: 3600)

2018-09-21T17:24:29.747306+00:00 app[web.1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)

2018-09-21T17:24:29.747308+00:00 app[web.1]: 	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)

2018-09-21T17:24:29.747309+00:00 app[web.1]: 	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)

2018-09-21T17:24:29.747310+00:00 app[web.1]: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)

2018-09-21T17:24:29.747312+00:00 app[web.1]: 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:59)

2018-09-21T17:24:29.747313+00:00 app[web.1]: 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:103)

2018-09-21T17:24:29.747315+00:00 app[web.1]: 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:149)

2018-09-21T17:24:29.747316+00:00 app[web.1]: 	at com.mysql.cj.exceptions.ExceptionFactory.createException(ExceptionFactory.java:127)

2018-09-21T17:24:29.747317+00:00 app[web.1]: 	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:819)

2018-09-21T17:24:29.747318+00:00 app[web.1]: 	at com.mysql.cj.protocol.a.NativeProtocol.checkErrorMessage(NativeProtocol.java:744)

2018-09-21T17:24:29.747320+00:00 app[web.1]: 	at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:674)

2018-09-21T17:24:29.747321+00:00 app[web.1]: 	at com.mysql.cj.protocol.a.NativeProtocol.sendCommand(NativeProtocol.java:135)

2018-09-21T17:24:29.747322+00:00 app[web.1]: 	at com.mysql.cj.NativeSession.sendCommand(NativeSession.java:319)

2018-09-21T17:24:29.747324+00:00 app[web.1]: 	at com.mysql.cj.NativeSession.loadServerVariables(NativeSession.java:853)

2018-09-21T17:24:29.747325+00:00 app[web.1]: 	at com.mysql.cj.jdbc.ConnectionImpl.initializePropsFromServer(ConnectionImpl.java:1379)

2018-09-21T17:24:29.747326+00:00 app[web.1]: 	at com.mysql.cj.jdbc.ConnectionImpl.connectWithRetries(ConnectionImpl.java:895)

2018-09-21T17:24:29.747328+00:00 app[web.1]: 	at com.mysql.cj.jdbc.ConnectionImpl.createNewIO(ConnectionImpl.java:857)

2018-09-21T17:24:29.747329+00:00 app[web.1]: 	at com.mysql.cj.jdbc.ConnectionImpl.<init>(ConnectionImpl.java:444)

2018-09-21T17:24:29.747331+00:00 app[web.1]: 	at com.mysql.cj.jdbc.ConnectionImpl.getInstance(ConnectionImpl.java:230)

2018-09-21T17:24:29.747332+00:00 app[web.1]: 	at com.mysql.cj.jdbc.NonRegisteringDriver.connect(NonRegisteringDriver.java:226)

2018-09-21T17:24:29.747333+00:00 app[web.1]: 	at java.sql.DriverManager.getConnection(DriverManager.java:664)

2018-09-21T17:24:29.747334+00:00 app[web.1]: 	at java.sql.DriverManager.getConnection(DriverManager.java:247)

2018-09-21T17:24:29.747335+00:00 app[web.1]: 	at csl.database.DatabaseHelper.getConnection(DatabaseHelper.java:82)

2018-09-21T17:24:29.747337+00:00 app[web.1]: 	at csl.database.DatabaseHelper.getConnection(DatabaseHelper.java:77)

2018-09-21T17:24:29.747338+00:00 app[web.1]: 	at org.springframework.jdbc.datasource.DataSourceUtils.fetchConnection(DataSourceUtils.java:151)

2018-09-21T17:24:29.747339+00:00 app[web.1]: 	at org.springframework.jdbc.datasource.DataSourceUtils.doGetConnection(DataSourceUtils.java:115)

2018-09-21T17:24:29.747341+00:00 app[web.1]: 	at org.springframework.jdbc.datasource.DataSourceUtils.getConnection(DataSourceUtils.java:78)

2018-09-21T17:24:29.747342+00:00 app[web.1]: 	at org.springframework.jdbc.core.JdbcTemplate.execute(JdbcTemplate.java:600)

2018-09-21T17:24:29.747343+00:00 app[web.1]: 	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:657)

2018-09-21T17:24:29.747345+00:00 app[web.1]: 	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:682)

2018-09-21T17:24:29.747346+00:00 app[web.1]: 	at org.springframework.jdbc.core.JdbcTemplate.query(JdbcTemplate.java:736)

2018-09-21T17:24:29.747347+00:00 app[web.1]: 	at org.springframework.jdbc.core.namedparam.NamedParameterJdbcTemplate.query(NamedParameterJdbcTemplate.java:211)

2018-09-21T17:24:29.747348+00:00 app[web.1]: 	at csl.database.PortionRepository.getPortion(PortionRepository.java:83)

2018-09-21T17:24:29.747350+00:00 app[web.1]: 	at csl.rest.ImportService.setAll(ImportService.java:72)

2018-09-21T17:24:29.747351+00:00 app[web.1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)

2018-09-21T17:24:29.747353+00:00 app[web.1]: 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)

2018-09-21T17:24:29.747354+00:00 app[web.1]: 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)

2018-09-21T17:24:29.747355+00:00 app[web.1]: 	at java.lang.reflect.Method.invoke(Method.java:498)

2018-09-21T17:24:29.747357+00:00 app[web.1]: 	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:209)

2018-09-21T17:24:29.747358+00:00 app[web.1]: 	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:136)

2018-09-21T17:24:29.747360+00:00 app[web.1]: 	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:102)

2018-09-21T17:24:29.747369+00:00 app[web.1]: 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:870)

2018-09-21T17:24:29.747370+00:00 app[web.1]: 	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:776)

2018-09-21T17:24:29.747371+00:00 app[web.1]: 	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:87)

2018-09-21T17:24:29.747373+00:00 app[web.1]: 	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:991)

2018-09-21T17:24:29.747374+00:00 app[web.1]: 	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:925)

2018-09-21T17:24:29.747376+00:00 app[web.1]: 	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:978)

2018-09-21T17:24:29.747377+00:00 app[web.1]: 	at org.springframework.web.servlet.FrameworkServlet.doPost(FrameworkServlet.java:881)

2018-09-21T17:24:29.747378+00:00 app[web.1]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:661)

2018-09-21T17:24:29.747380+00:00 app[web.1]: 	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:855)

2018-09-21T17:24:29.747381+00:00 app[web.1]: 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:742)

2018-09-21T17:24:29.747382+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:231)

2018-09-21T17:24:29.747384+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

2018-09-21T17:24:29.747385+00:00 app[web.1]: 	at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

2018-09-21T17:24:29.747386+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)

2018-09-21T17:24:29.747387+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

2018-09-21T17:24:29.747389+00:00 app[web.1]: 	at csl.security.SecurityFilter.doFilter(SecurityFilter.java:68)

2018-09-21T17:24:29.747390+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)

2018-09-21T17:24:29.747391+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

2018-09-21T17:24:29.747393+00:00 app[web.1]: 	at org.springframework.web.filter.RequestContextFilter.doFilterInternal(RequestContextFilter.java:99)

2018-09-21T17:24:29.747394+00:00 app[web.1]: 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)

2018-09-21T17:24:29.747396+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)

2018-09-21T17:24:29.747397+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

2018-09-21T17:24:29.747398+00:00 app[web.1]: 	at org.springframework.web.filter.HttpPutFormContentFilter.doFilterInternal(HttpPutFormContentFilter.java:109)

2018-09-21T17:24:29.747400+00:00 app[web.1]: 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)

2018-09-21T17:24:29.747401+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)

2018-09-21T17:24:29.747402+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

2018-09-21T17:24:29.747403+00:00 app[web.1]: 	at org.springframework.web.filter.HiddenHttpMethodFilter.doFilterInternal(HiddenHttpMethodFilter.java:81)

2018-09-21T17:24:29.747405+00:00 app[web.1]: 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)

2018-09-21T17:24:29.747406+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)

2018-09-21T17:24:29.747407+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

2018-09-21T17:24:29.747409+00:00 app[web.1]: 	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:200)

2018-09-21T17:24:29.747410+00:00 app[web.1]: 	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)

2018-09-21T17:24:29.747411+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)

2018-09-21T17:24:29.747413+00:00 app[web.1]: 	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)

2018-09-21T17:24:29.747414+00:00 app[web.1]: 	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:199)

2018-09-21T17:24:29.747415+00:00 app[web.1]: 	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:96)

2018-09-21T17:24:29.747417+00:00 app[web.1]: 	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:496)

2018-09-21T17:24:29.747418+00:00 app[web.1]: 	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:140)

2018-09-21T17:24:29.747419+00:00 app[web.1]: 	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:81)

2018-09-21T17:24:29.747420+00:00 app[web.1]: 	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:87)

2018-09-21T17:24:29.747422+00:00 app[web.1]: 	at org.apache.catalina.valves.RemoteIpValve.invoke(RemoteIpValve.java:677)

2018-09-21T17:24:29.747423+00:00 app[web.1]: 	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:342)

2018-09-21T17:24:29.747425+00:00 app[web.1]: 	at org.apache.coyote.http11.Http11Processor.service(Http11Processor.java:803)

2018-09-21T17:24:29.747430+00:00 app[web.1]: 	at org.apache.coyote.AbstractProcessorLight.process(AbstractProcessorLight.java:66)

2018-09-21T17:24:29.747432+00:00 app[web.1]: 	at org.apache.coyote.AbstractProtocol$ConnectionHandler.process(AbstractProtocol.java:790)

2018-09-21T17:24:29.747433+00:00 app[web.1]: 	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1459)

2018-09-21T17:24:29.747434+00:00 app[web.1]: 	at org.apache.tomcat.util.net.SocketProcessorBase.run(SocketProcessorBase.java:49)

2018-09-21T17:24:29.747436+00:00 app[web.1]: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)

2018-09-21T17:24:29.747438+00:00 app[web.1]: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)

2018-09-21T17:24:29.747439+00:00 app[web.1]: 	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61)

2018-09-21T17:24:29.747441+00:00 app[web.1]: 	at java.lang.Thread.run(Thread.java:748)

**Comment by atienkamp** [comment]
https://devcenter.heroku.com/articles/jawsdb#i-am-getting-an-error-saying-i-have-exceeded-the-max_questions-resource-what-is-that

**Comment by CarmenScholte** [comment]
Refactor import service:

Na inserten food en portions, lijst ophalen van alle food, in plaats van bij iedere insert logentry food id uit de database querien.

**Comment by atienkamp** [comment]
Import succesvol, maar timeout bij aanroepen:
```
2018-09-22T08:43:36.804949+00:00 heroku[router]: at=error code=H12 desc="Request timeout" method=POST path="/import" host=macrolog-backend.herokuapp.com request_id=e6b8e52f-dfb9-4cd6-9d17-f026ef011a05 fwd="94.212.42.153" dyno=web.1 connect=3ms service=30007ms status=503 bytes=0 protocol=https
